In [ ]:
                                                            #Heart Disease Risk Assessment

In [ ]:
#import libraries

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [4]:
# Heart Disease Dataset

In [5]:
data = {
    "age": [63,37,41,56,57,57,56,44,52,57,54,48,49,64,58,50,58,66,43,69],
    "sex": [1,1,0,1,0,1,0,1,1,0,1,0,1,1,0,1,1,0,1,0],
    "cp": [3,2,1,1,0,0,1,1,2,0,2,1,2,3,2,1,0,2,1,3],
    "trestbps": [145,130,130,120,120,140,140,120,172,150,140,130,130,110,150,120,120,150,130,140],
    "chol": [233,250,204,236,354,192,294,263,199,168,239,275,266,211,283,219,340,226,247,239],
    "thalach": [150,187,172,178,163,148,153,173,162,174,160,139,171,144,162,158,172,114,171,151],
    "target": [1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,0,1,0]
}

In [6]:
# Create DataFrame

In [7]:
df = pd.DataFrame(data)
df.head()

   age  sex  cp  trestbps  chol  thalach  target
0   63    1   3       145   233      150       1
1   37    1   2       130   250      187       1
2   41    0   1       130   204      172       1
3   56    1   1       120   236      178       1
4   57    0   0       120   354      163       1

In [8]:
# Features and Target

In [9]:
X = df.drop("target", axis=1)
y = df["target"]
X.head()

   age  sex  cp  trestbps  chol  thalach
0   63    1   3       145   233      150
1   37    1   2       130   250      187
2   41    0   1       130   204      172
3   56    1   1       120   236      178
4   57    0   0       120   354      163

In [10]:
# Split Data

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(X_train.shape)
print(X_test.shape)

(16, 6)
(4, 6)

In [12]:
# Decision Tree Model

In [13]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
print("desicion tree accuracy:",accuracy_score(y_test,dt_pred))

desicion tree accuracy: 0.5

In [14]:
# Random Forest Model

In [15]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Random Forest Accuracy:",accuracy_score(y_test,rf_pred))

Random Forest Accuracy: 0.5

In [16]:
# Feature Importance (Random Forest)

In [17]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)

print("\nFeature Importance:")
print(importance)

Feature Importance:
    Feature  Importance
0       age    0.418660
2        cp    0.231257
3  trestbps    0.118849
5   thalach    0.106543
4      chol    0.097452
1       sex    0.027239

In [18]:
# Most and Least Important Feature

In [19]:
print("\nMost Important Feature:")
print(importance.iloc[0])

print("\nLeast Important Feature:")
print(importance.iloc[-1])

Most Important Feature:
Feature           age
Importance    0.41866
Name: 0, dtype: object

Least Important Feature:
Feature            sex
Importance    0.027239
Name: 1, dtype: object

In [20]:
#csv file created

In [25]:
df.to_csv("Heart Disease Risk Assessment.csv")
print("Heart Disease Risk Assessment created successfully")
most_important=importance.iloc[[0]]
most_important.to_csv("most_important_feature.csv", index=False)
least_important = importance.iloc[[-1]]
least_important.to_csv("least_important_feature.csv", index=False)

Heart Disease Risk Assessment created successfully